name: pull-request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Lint
        run: pnpm lint

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Check format
        run: pnpm check:format

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Typecheck
        run: pnpm check:types
